title: Predicting Box Office Performance from Movie Trailer Comments
description: Sahil Bishnoi, Rishidhar Duvvuru, Oliver Hewett, Nathan Popper, Chandler Schneider
show_downloads: false
theme: jekyll-theme-cayman